# Generated by Django 4.1.3 on 2022-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads')),
                ('content', models.TextField()),
            ],
        ),
    ]
